### ISSUE TITLE
Breaks Media Queries

### ISSUE THREAD

**Issue by erickeno** [johnuphoff/vscode-styled-sort#8]
**Describe the bug**
When sorting and media queries are present, it moves the defined style out of the media query closure and also sorts the brackets as well.

Device: Macbook
VS Code version: 1.26.0 (1.26.0)
Using Typescript.

![kapture 2018-08-17 at 14 36 11](https://user-images.githubusercontent.com/3820632/44285504-4170b900-a22b-11e8-97c7-ebf7ea93cda2.gif)

**Comment by johnuphoff** [comment]
Thanks / I’m on it.

**Comment by johnuphoff** [comment]
Please upgrade to 0.0.6 - thanks!

**Comment by johnuphoff** [comment]
Also I should mention that I changed the order a bit just slightly.  It shouldn't affect you hopefully but vendor prefixes now go directly after alphabetical rules.  Media queries go to the very end.  The plugin does not currently support deeper nesting (media query inside pseudo selector for example).  If that is an issue or if you need anything else let me know!
